#!/bin/bash

v1_mac="$(ifconfig | grep 'veth1 ' -C 0 | cut -d' ' -f10)"
v2_mac="$(ifconfig | grep 'veth2 ' -C 0 | cut -d' ' -f10)"
v3_mac="$(ifconfig | grep 'veth3 ' -C 0 | cut -d' ' -f10)"
v4_mac="$(ifconfig | grep 'veth4 ' -C 0 | cut -d' ' -f10)"
v5_mac="$(ifconfig | grep 'veth5 ' -C 0 | cut -d' ' -f10)"
v6_mac="$(ifconfig | grep 'veth6 ' -C 0 | cut -d' ' -f10)"
v7_mac="$(ifconfig | grep 'veth7 ' -C 0 | cut -d' ' -f10)"
v8_mac="$(ifconfig | grep 'veth8 ' -C 0 | cut -d' ' -f10)"
v9_mac="$(ifconfig | grep 'veth9 ' -C 0 | cut -d' ' -f10)"
v10_mac="$(ifconfig | grep 'veth10 ' -C 0 | cut -d' ' -f9)"
v11_mac="$(ifconfig | grep 'veth11 ' -C 0 | cut -d' ' -f9)"
v12_mac="$(ifconfig | grep 'veth12 ' -C 0 | cut -d' ' -f9)"
v13_mac="$(ifconfig | grep 'veth13 ' -C 0 | cut -d' ' -f9)"
v14_mac="$(ifconfig | grep 'veth14 ' -C 0 | cut -d' ' -f9)"
v15_mac="$(ifconfig | grep 'veth15 ' -C 0 | cut -d' ' -f9)"
v16_mac="$(ifconfig | grep 'veth16 ' -C 0 | cut -d' ' -f9)"
v17_mac="$(ifconfig | grep 'veth17 ' -C 0 | cut -d' ' -f9)"
v18_mac="$(ifconfig | grep 'veth18 ' -C 0 | cut -d' ' -f9)"
v19_mac="$(ifconfig | grep 'veth19 ' -C 0 | cut -d' ' -f9)"
v20_mac="$(ifconfig | grep 'veth20 ' -C 0 | cut -d' ' -f9)"
